### PR TITLE
PL-2776 bootstrapper - deployment on GitHub have {"error":"no respons…

### PR DESCRIPTION
**Pull request by marcinbridge**
https://vsf.atlassian.net/browse/PL-2776

### CODE REVIEW

**Review by RetroModernDev — COMMENTED** [review]
This will work only for new instances. What with existing ones?
And why do we need to add this timeout? Can you elaborate? I want to understand what is going on here.

**Comment by RetroModernDev** [comment]
We have a few variations of this template: 
With middleware: https://github.com/vuestorefront/sample-express-application-with-middleware
Stage: https://github.com/vuestorefront/sample-express-application-stage
Stage with middleware: https://github.com/vuestorefront/sample-express-application-with-middleware-stage 

If we need these changes, it should be added to each repository.

**Comment by marcinbridge** [comment]
> We have a few variations of this template: With middleware: https://github.com/vuestorefront/sample-express-application-with-middleware Stage: https://github.com/vuestorefront/sample-express-application-stage Stage with middleware: https://github.com/vuestorefront/sample-express-application-with-middleware-stage
> 
> If we need these changes, it should be added to each repository.

Yesterday, I created pull requests for them but during the push, I had to communicate that I have no permission. If this is not a problem, please give my user access to push to those repositories

**Comment by marcinbridge** [comment]
> This will work only for new instances. What with existing ones? And why do we need to add this timeout? Can you elaborate? I want to understand what is going on here.

Currently, Farmer Api's response time increased way above 5 seconds and because of that platform backend, which is dependent, response time grew also. The situation requires further investigation. It will be a good candidate for migration to the new nestjs Gandalf api

**Review by RetroModernDev — APPROVED** [review]

**Pull request merged**
